#!/bin/bash

current_dir="$HOME/Workspace/global/workspace-switcher"
echo $current_dir

num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' | rofi -dmenu -p "Workspace Switcher" -theme $current_dir/theme| cut -d '-' -f -1)
echo $num
[[ -z "$num" ]] && exit
wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -a
